
depositGroup=logger_group_deposit-test
depositTopic=topic.OracleDataLogger
kafkaHostServer=${KAFKA_HOST_SERVER}
maxPollIntervalMs=300000
maxPollRecords=50

dbUrl=${CONFIG_DB_URL}
dbUsername=${CONFIG_DB_USERNAME}
dbPassword=${CONFIG_DB_PASSWORD}

maximumPoolSize=13
connectionTimeout=300000

alertAddresses=user@example.com,user2@example.com
fromEmail=support@example.com
environmentName=DEV
mailHost=127.0.0.1
mailPort=25
