config.odeUrl=${CONFIG_ODE_URL}
config.cvRestService=${CONFIG_CV_REST_SERVICE}
config.rsuDataServiceUrl=${CONFIG_RSU_DATA_SERVICE_URL}
config.wrapperUrl=${CONFIG_WRAPPER_URL}
config.sdwRestUrl=${CONFIG_SDW_REST_URL}
config.sdwApiKey=${CONFIG_SDW_API_KEY}
config.tmddUrl=${CONFIG_TMDD_URL}
config.tmddUser=${CONFIG_TMDD_USER}
config.tmddPassword=${CONFIG_TMDD_PASSWORD}
config.alertAddresses=user@example.com,user2@example.com
config.fromEmail=support@example.com
config.environmentName=${CONFIG_ENVIRONMENT_NAME:DEV}
config.mailHost=${CONFIG_MAIL_HOST}
config.mailPort=25
config.runTmddValidation=true
config.runRsuValidation=true
config.rsuValidationDelaySeconds=60
config.rsuValThreadPoolSize=76
config.rsuValTimeoutSeconds=300
config.removeExpiredPeriodMinutes=240
config.cleanupPeriodMinutes=240
config.sdxValidationPeriodMinutes=1440
config.rsuValidationPeriodMinutes=1440
config.tmddValidationPeriodMinutes=1440
config.retentionEnforcementPeriodMinutes=1440
config.retention_removeTims = true
config.retention_removeStatusLogs = false
config.hsmFunctionalityMinutes=1
config.hsmUrl=${CONFIG_HSM_URL}
config.hsmErrorEmailFrequencyMinutes=10
config.runHsmCheck=true
config.sdwTtl=oneyear
config.defaultLaneWidth=50
config.rsuRoutes = route1, route2
config.pointIncidentBufferMiles=1
config.cleanupStaleActiveTimHoldingRecordsPeriodMinutes=60