kafkaHostServer=${KAFKA_HOST_SERVER}
alertAddresses=user@example.com,user2@example.com
fromEmail=support@example.com
environmentName=${CONFIG_ENVIRONMENT_NAME}
mailHost=${CONFIG_MAIL_HOST}
mailPort=${CONFIG_MAIL_PORT}
depositTopic=topic.OdeTimJson
depositGroup=logger_group_tim_dev
cvRestService=${CONFIG_CV_REST_SERVICE}
producerTopic=topic.OracleDataLogger