version: '2'
services:
  ode_wrapper:
    build: ode-wrapper
    restart: always
    environment:
      CONFIG_ODE_URL: ${WRAPPER_CONFIG_ODE_URL}
      CONFIG_DB_DRIVER: ${WRAPPER_CONFIG_DB_DRIVER}
      CONFIG_DB_URL: ${WRAPPER_CONFIG_DB_URL}
      CONFIG_DB_USERNAME: ${WRAPPER_CONFIG_DB_USERNAME}
      CONFIG_DB_PASSWORD: ${WRAPPER_CONFIG_DB_PASSWORD}
      CONFIG_ENV: ${WRAPPER_CONFIG_ENV}
      CONFIG_SDW_TTL: ${WRAPPER_CONFIG_SDW_TTL}
      CONFIG_SDW_REST_URL: ${WRAPPER_CONFIG_SDW_REST_URL}
      CONFIG_SDW_API_KEY: ${WRAPPER_CONFIG_SDW_API_KEY}
      CONFIG_ALERT_ADDRESSES: ${WRAPPER_CONFIG_ALERT_ADDRESSES}
      CONFIG_FROM_EMAIL: ${WRAPPER_CONFIG_FROM_EMAIL}
      CONFIG_MAIL_HOST: ${WRAPPER_CONFIG_MAIL_HOST}
      CONFIG_MAIL_PORT: ${WRAPPER_CONFIG_MAIL_PORT}
      CONFIG_DEFAULT_LANE_WIDTH: ${WRAPPER_CONFIG_DEFAULT_LANE_WIDTH}
    ports:
      - "7777:7777"

  cv-data-tasks: 
    build: cv-data-tasks

  tim-refresh:
    build: tim-refresh

  cv-data-controller:
    build: cv-data-controller
    restart: always
    ports:
      - "8888:8888"

  angular: 
    build: timBuilder 
    restart: always
    ports: 
      - "4200:4200"

  bsm_logger_mongo:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${BSM_TOPIC}
      DEPOSIT_GROUP: ${BSM_GROUP_MONGO}
    logging:
      options:
        max-size: 50m

  bsm_logger_mongo_2:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${BSM_TOPIC}
      DEPOSIT_GROUP: ${BSM_GROUP_MONGO}
    logging:
      options:
        max-size: 50m

  bsm_logger:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${BSM_TOPIC}
      DEPOSIT_GROUP: ${BSM_GROUP_ORACLE}
    logging:
      options:
        max-size: 50m

  bsm_logger_2:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${BSM_TOPIC}
      DEPOSIT_GROUP: ${BSM_GROUP_ORACLE}
    logging:
      options:
        max-size: 50m

  tim_logger_mongo:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${TIM_TOPIC}
      DEPOSIT_GROUP: ${TIM_GROUP_MONGO}
    logging:
      options:
        max-size: 50m
  
  tim_logger_mongo_2:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${TIM_TOPIC}
      DEPOSIT_GROUP: ${TIM_GROUP_MONGO}
    logging:
      options:
        max-size: 50m

  tim_logger:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${TIM_TOPIC}
      DEPOSIT_GROUP: ${TIM_GROUP_ORACLE}
    logging:
      options:
        max-size: 50m


  tim_logger_2:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${TIM_TOPIC}
      DEPOSIT_GROUP: ${TIM_GROUP_ORACLE}
    logging:
      options:
        max-size: 50m

  da_logger_mongo:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${DA_TOPIC}
      DEPOSIT_GROUP: ${DA_GROUP_MONGO}
    logging:
      options:
        max-size: 50m


  da_logger_mongo_2:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${DA_TOPIC}
      DEPOSIT_GROUP: ${DA_GROUP_MONGO}
    logging:
      options:
        max-size: 50m

  da_logger:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${DA_TOPIC}
      DEPOSIT_GROUP: ${DA_GROUP_ORACLE}
    logging:
      options:
        max-size: 50m

  da_logger_2:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${DA_TOPIC}
      DEPOSIT_GROUP: ${DA_GROUP_ORACLE}
    logging:
      options:
        max-size: 50m      

  dn_trac_sender:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${DN_TOPIC}
      DEPOSIT_GROUP: ${DN_GROUP}
    logging:
      options:
        max-size: 50m

  ode-wrapper-docs:
    build: ode-wrapper-docs/swagger-ui-master
    restart: always
    logging:
      options:
        max-size: 50m
    ports:
      - "9999:9999"

  smdm: 
    build: smdm 
    restart: always
    logging:
      options:
        max-size: 50m 
    ports:
      - "8081:8081"