version: '2'
services:
  ode_wrapper:
    build: ode-wrapper
    restart: always
    ports:
      - "7777:7777"

  cv-data-tasks: 
    build: cv-data-tasks

  tim-refresh:
    build: tim-refresh

  cv-data-controller:
    build: cv-data-controller
    restart: always
    ports:
      - "8888:8888"

  angular: 
    build: timBuilder 
    restart: always
    ports: 
      - "4200:4200"

  bsm_logger_mongo:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeBsmJson
      DEPOSIT_GROUP: group_bsm_mongo_logger
    logging:
      options:
        max-size: 50m

  bsm_logger_mongo_2:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeBsmJson
      DEPOSIT_GROUP: group_bsm_mongo_logger
    logging:
      options:
        max-size: 50m

  bsm_logger:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeBsmJson
      DEPOSIT_GROUP: group_bsm_logger
    logging:
      options:
        max-size: 50m

  bsm_logger_2:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeBsmJson
      DEPOSIT_GROUP: group_bsm_logger
    logging:
      options:
        max-size: 50m
  
        #broadcast_tim_logger:
        #    build: ode-data-logger
        #    environment:
        #      DEPOSIT_TOPIC: topic.OdeTimBroadcastJson
        #      DEPOSIT_GROUP: group_broadcast_tim_logger
        #    logging:
        #      options:
        #        max-size: 50m

  tim_logger_mongo:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeTimJson
      DEPOSIT_GROUP: group_tim_mongo_logger
    logging:
      options:
        max-size: 50m
  
  tim_logger_mongo_2:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeTimJson
      DEPOSIT_GROUP: group_tim_mongo_logger
    logging:
      options:
        max-size: 50m

  tim_logger:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeTimJson
      DEPOSIT_GROUP: group_tim_logger
    logging:
      options:
        max-size: 50m


  tim_logger_2:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeTimJson
      DEPOSIT_GROUP: group_tim_logger
    logging:
      options:
        max-size: 50m

        #  tim_logger_3:
        #    build: ode-data-logger
        #    environment:
        #      DEPOSIT_TOPIC: topic.OdeTimJson
        #      DEPOSIT_GROUP: group_tim_logger
        #    logging:
        #      options:
        #        max-size: 50m

  da_logger_mongo:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeDriverAlertJson
      DEPOSIT_GROUP: group_da_mongo_logger
    logging:
      options:
        max-size: 50m


  da_logger_mongo_2:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeDriverAlertJson
      DEPOSIT_GROUP: group_da_mongo_logger
    logging:
      options:
        max-size: 50m

  da_logger:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeDriverAlertJson
      DEPOSIT_GROUP: group_da_logger
    logging:
      options:
        max-size: 50m

  da_logger_2:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeDriverAlertJson
      DEPOSIT_GROUP: group_da_logger
    logging:
      options:
        max-size: 50m      

  dn_trac_sender:
    build: ode-data-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: topic.OdeDNMsgJson
      DEPOSIT_GROUP: group_dn_sender
    logging:
      options:
        max-size: 50m

  ode-wrapper-docs:
    build: ode-wrapper-docs/swagger-ui-master
    restart: always
    logging:
      options:
        max-size: 50m
    ports:
      - "9999:9999"

  smdm: 
    build: smdm 
    restart: always
    logging:
      options:
        max-size: 50m 
    ports:
      - "8081:8081"


