version: "2"
services:
  ode_wrapper:
    build: ode-wrapper
    restart: always
    environment:
      SERVER_PORT: ${WRAPPER_SERVER_PORT}
      CONFIG_ODE_URL: ${WRAPPER_CONFIG_ODE_URL}
      CONFIG_DB_DRIVER: ${WRAPPER_CONFIG_DB_DRIVER}
      CONFIG_DB_URL: ${WRAPPER_CONFIG_DB_URL}
      CONFIG_DB_USERNAME: ${WRAPPER_CONFIG_DB_USERNAME}
      CONFIG_DB_PASSWORD: ${WRAPPER_CONFIG_DB_PASSWORD}
      CONFIG_ENV: ${WRAPPER_CONFIG_ENV}
      CONFIG_SDW_TTL: ${WRAPPER_CONFIG_SDW_TTL}
      CONFIG_SDW_REST_URL: ${WRAPPER_CONFIG_SDW_REST_URL}
      CONFIG_SDW_API_KEY: ${WRAPPER_CONFIG_SDW_API_KEY}
      CONFIG_ALERT_ADDRESSES: ${WRAPPER_CONFIG_ALERT_ADDRESSES}
      CONFIG_FROM_EMAIL: ${WRAPPER_CONFIG_FROM_EMAIL}
      CONFIG_MAIL_HOST: ${MAIL_HOST}
      CONFIG_MAIL_PORT: ${MAIL_PORT}
      CONFIG_DEFAULT_LANE_WIDTH: ${WRAPPER_CONFIG_DEFAULT_LANE_WIDTH}
      CONFIG_CV_REST_SERVICE: ${WRAPPER_CONFIG_CV_REST_SERVICE}
      CONFIG_RSU_ROUTES: ${WRAPPER_CONFIG_RSU_ROUTES}
      # THE FOLLOWING ARE ONLY USED IN PRODUCTION:
      # SERVER_SSL_KEY_STORE: ${WRAPPER_SERVER_SSL_KEY_STORE}
      # SERVER_SSL_KEY_STORE_PASSWORD: ${WRAPPER_SERVER_SSL_KEY_STORE_PASSWORD}
      # SERVER_SSL_KEY_STORE_TYPE: ${WRAPPER_SERVER_SSL_KEY_STORE_TYPE}
      # SERVER_SSL_KEY_ALIAS: ${WRAPPER_SERVER_SSL_KEY_ALIAS}
    ports:
      - "7777:7777"

  cv-data-tasks:
    build: cv-data-tasks
    restart: always
    environment:
      CONFIG_ODE_URL: ${TASKS_CONFIG_ODE_URL}
      CONFIG_CV_REST_SERVICE: ${TASKS_CONFIG_CV_REST_SERVICE}
      CONFIG_WRAPPER_URL: ${TASKS_CONFIG_WRAPPER_URL}
      CONFIG_ENV: ${TASKS_CONFIG_ENV}

  tim-refresh:
    build: tim-refresh
    restart: always
    environment:
      CONFIG_ODE_URL: ${REFRESH_CONFIG_ODE_URL}
      CONFIG_SDW_TTL: ${REFRESH_CONFIG_SDW_TTL}
      CONFIG_CV_REST_SERVICE: ${REFRESH_CONFIG_CV_REST_SERVICE}
      CONFIG_SDW_REST_URL: ${REFRESH_CONFIG_SDW_REST_URL}
      CONFIG_SDW_API_KEY: ${REFRESH_CONFIG_SDW_API_KEY}
      CONFIG_DEFAULT_LANE_WIDTH: ${REFRESH_CONFIG_DEFAULT_LANE_WIDTH}
      CRON_EXPRESSION: ${REFRESH_CRON_EXPRESSION}
      CONFIG_ENV: ${REFRESH_CONFIG_ENV}

  cv-data-controller:
    build: cv-data-controller
    restart: always
    ports:
      - "8888:8888"
    environment:
      SERVER_PORT: ${CONTROLLER_SERVER_PORT}
      CONFIG_DB_DRIVER: ${CONTROLLER_CONFIG_DB_DRIVER}
      CONFIG_DB_URL: ${CONTROLLER_CONFIG_DB_URL}
      CONFIG_DB_USERNAME: ${CONTROLLER_CONFIG_DB_USERNAME}
      CONFIG_DB_PASSWORD: ${CONTROLLER_CONFIG_DB_PASSWORD}
      CONFIG_POOL_SIZE: ${CONTROLLER_CONFIG_POOL_SIZE}
      CONFIG_ODE_URL: ${CONTROLLER_CONFIG_ODE_URL}
      CONFIG_ENV: ${CONTROLLER_CONFIG_ENV}
      SPRING_DATA_NEO4J_URI: ${CONTROLLER_SPRING_DATA_NEO4J_URI}

  rsu-data-controller:
    build: rsu-data-controller
    restart: always
    ports:
      - "8898:8898"
    environment:
      SERVER_PORT: ${RSUCONTROLLER_SERVER_PORT}
      CONFIG_SNMP_RETRIES: ${RSUCONTROLLER_CONFIG_SNMP_RETRIES}
      CONFIG_SNMP_TIMEOUT_SECONDS: ${RSUCONTROLLER_CONFIG_SNMP_TIMEOUT_SECONDS}
      CONFIG_SNMP_USER_NAME: ${RSUCONTROLLER_CONFIG_SNMP_USER_NAME}
      CONFIG_SNMP_AUTH_PASSPHRASE: ${RSUCONTROLLER_CONFIG_SNMP_AUTH_PASSPHRASE}
      CONFIG_SNMP_AUTH_PROTOCOL: ${RSUCONTROLLER_CONFIG_SNMP_AUTH_PROTOCOL}
      CONFIG_SNMP_SECURITY_LEVEL: ${RSUCONTROLLER_CONFIG_SNMP_SECURITY_LEVEL}

  angular:
    build: timBuilder
    restart: always
    ports:
      - "4200:4200"

  bsm_logger_mongo:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${BSM_TOPIC}
      DEPOSIT_GROUP: ${BSM_GROUP_MONGO}
      HOSTNAME: ${MONGO_HOSTNAME}
      ENV: ${MONGO_ENV}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      ALERT_ADDRESSES: ${MONGO_ALERT_ADDRESSES}
      FROM_EMAIL: ${MONGO_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
    logging:
      options:
        max-size: 50m

  bsm_logger_mongo_2:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${BSM_TOPIC}
      DEPOSIT_GROUP: ${BSM_GROUP_MONGO}
      HOSTNAME: ${MONGO_HOSTNAME}
      ENV: ${MONGO_ENV}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      ALERT_ADDRESSES: ${MONGO_ALERT_ADDRESSES}
      FROM_EMAIL: ${MONGO_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
    logging:
      options:
        max-size: 50m

  bsm_logger:
    build: ode-data-logger
    restart: always
    environment:
      KAFKA_HOST_SERVER: ${LOGGER_KAFKA_HOST_SERVER}
      TRAC_URL: ${LOGGER_TRAC_URL}
      ALERT_ADDRESSES: ${LOGGER_ALERT_ADDRESSES}
      FROM_EMAIL: ${LOGGER_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      DEPOSIT_TOPIC: ${BSM_TOPIC}
      DEPOSIT_GROUP: ${BSM_GROUP_ORACLE}
      CV_REST_SERVICE: ${LOGGER_CV_REST_SERVICE}
      PRODUCER_TOPIC: ${DBCONSUMER_DEPOSIT_TOPIC}
      ENV: ${LOGGER_ENV}
    logging:
      options:
        max-size: 50m

  bsm_logger_2:
    build: ode-data-logger
    restart: always
    environment:
      KAFKA_HOST_SERVER: ${LOGGER_KAFKA_HOST_SERVER}
      TRAC_URL: ${LOGGER_TRAC_URL}
      ALERT_ADDRESSES: ${LOGGER_ALERT_ADDRESSES}
      FROM_EMAIL: ${LOGGER_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      DEPOSIT_TOPIC: ${BSM_TOPIC}
      DEPOSIT_GROUP: ${BSM_GROUP_ORACLE}
      CV_REST_SERVICE: ${LOGGER_CV_REST_SERVICE}
      PRODUCER_TOPIC: ${DBCONSUMER_DEPOSIT_TOPIC}
      ENV: ${LOGGER_ENV}
    logging:
      options:
        max-size: 50m

  tim_logger_mongo:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${TIM_TOPIC}
      DEPOSIT_GROUP: ${TIM_GROUP_MONGO}
      HOSTNAME: ${MONGO_HOSTNAME}
      ENV: ${MONGO_ENV}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      ALERT_ADDRESSES: ${MONGO_ALERT_ADDRESSES}
      FROM_EMAIL: ${MONGO_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
    logging:
      options:
        max-size: 50m

  tim_logger_mongo_2:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${TIM_TOPIC}
      DEPOSIT_GROUP: ${TIM_GROUP_MONGO}
      HOSTNAME: ${MONGO_HOSTNAME}
      ENV: ${MONGO_ENV}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      ALERT_ADDRESSES: ${MONGO_ALERT_ADDRESSES}
      FROM_EMAIL: ${MONGO_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
    logging:
      options:
        max-size: 50m

  tim_logger:
    build: ode-data-logger
    restart: always
    environment:
      KAFKA_HOST_SERVER: ${LOGGER_KAFKA_HOST_SERVER}
      TRAC_URL: ${LOGGER_TRAC_URL}
      ALERT_ADDRESSES: ${LOGGER_ALERT_ADDRESSES}
      FROM_EMAIL: ${LOGGER_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      DEPOSIT_TOPIC: ${TIM_TOPIC}
      DEPOSIT_GROUP: ${TIM_GROUP_ORACLE}
      CV_REST_SERVICE: ${LOGGER_CV_REST_SERVICE}
      PRODUCER_TOPIC: ${DBCONSUMER_DEPOSIT_TOPIC}
      ENV: ${LOGGER_ENV}
    logging:
      options:
        max-size: 50m

  tim_logger_2:
    build: ode-data-logger
    restart: always
    environment:
      KAFKA_HOST_SERVER: ${LOGGER_KAFKA_HOST_SERVER}
      TRAC_URL: ${LOGGER_TRAC_URL}
      ALERT_ADDRESSES: ${LOGGER_ALERT_ADDRESSES}
      FROM_EMAIL: ${LOGGER_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      DEPOSIT_TOPIC: ${TIM_TOPIC}
      DEPOSIT_GROUP: ${TIM_GROUP_ORACLE}
      CV_REST_SERVICE: ${LOGGER_CV_REST_SERVICE}
      PRODUCER_TOPIC: ${DBCONSUMER_DEPOSIT_TOPIC}
      ENV: ${LOGGER_ENV}
    logging:
      options:
        max-size: 50m

  da_logger_mongo:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${DA_TOPIC}
      DEPOSIT_GROUP: ${DA_GROUP_MONGO}
      HOSTNAME: ${MONGO_HOSTNAME}
      ENV: ${MONGO_ENV}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      ALERT_ADDRESSES: ${MONGO_ALERT_ADDRESSES}
      FROM_EMAIL: ${MONGO_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
    logging:
      options:
        max-size: 50m

  da_logger_mongo_2:
    build: ode-mongo-logger
    restart: always
    environment:
      DEPOSIT_TOPIC: ${DA_TOPIC}
      DEPOSIT_GROUP: ${DA_GROUP_MONGO}
      HOSTNAME: ${MONGO_HOSTNAME}
      ENV: ${MONGO_ENV}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      ALERT_ADDRESSES: ${MONGO_ALERT_ADDRESSES}
      FROM_EMAIL: ${MONGO_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
    logging:
      options:
        max-size: 50m

  da_logger:
    build: ode-data-logger
    restart: always
    environment:
      KAFKA_HOST_SERVER: ${LOGGER_KAFKA_HOST_SERVER}
      TRAC_URL: ${LOGGER_TRAC_URL}
      ALERT_ADDRESSES: ${LOGGER_ALERT_ADDRESSES}
      FROM_EMAIL: ${LOGGER_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      DEPOSIT_TOPIC: ${DA_TOPIC}
      DEPOSIT_GROUP: ${DA_GROUP_ORACLE}
      CV_REST_SERVICE: ${LOGGER_CV_REST_SERVICE}
      PRODUCER_TOPIC: ${DBCONSUMER_DEPOSIT_TOPIC}
      ENV: ${LOGGER_ENV}
    logging:
      options:
        max-size: 50m

  da_logger_2:
    build: ode-data-logger
    restart: always
    environment:
      KAFKA_HOST_SERVER: ${LOGGER_KAFKA_HOST_SERVER}
      TRAC_URL: ${LOGGER_TRAC_URL}
      ALERT_ADDRESSES: ${LOGGER_ALERT_ADDRESSES}
      FROM_EMAIL: ${LOGGER_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      DEPOSIT_TOPIC: ${DA_TOPIC}
      DEPOSIT_GROUP: ${DA_GROUP_ORACLE}
      CV_REST_SERVICE: ${LOGGER_CV_REST_SERVICE}
      PRODUCER_TOPIC: ${DBCONSUMER_DEPOSIT_TOPIC}
      ENV: ${LOGGER_ENV}
    logging:
      options:
        max-size: 50m

  dn_trac_sender:
    build: ode-data-logger
    restart: always
    environment:
      KAFKA_HOST_SERVER: ${LOGGER_KAFKA_HOST_SERVER}
      TRAC_URL: ${LOGGER_TRAC_URL}
      ALERT_ADDRESSES: ${LOGGER_ALERT_ADDRESSES}
      FROM_EMAIL: ${LOGGER_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      DEPOSIT_TOPIC: ${DN_TOPIC}
      DEPOSIT_GROUP: ${DN_GROUP}
      CV_REST_SERVICE: ${LOGGER_CV_REST_SERVICE}
      PRODUCER_TOPIC: ${DBCONSUMER_DEPOSIT_TOPIC}
      ENV: ${LOGGER_ENV}
    logging:
      options:
        max-size: 50m

  smdm:
    build: smdm
    restart: always
    logging:
      options:
        max-size: 50m
    ports:
      - "8081:8081"

  logger-kafka-consumer:
    build: logger-kafka-consumer
    restart: always
    environment:
      DEPOSIT_GROUP: ${DBCONSUMER_DEPOSIT_GROUP}
      DEPOSIT_TOPIC: ${DBCONSUMER_DEPOSIT_TOPIC}
      KAFKA_HOST_SERVER: ${DBCONSUMER_KAFKA_HOST_SERVER}
      DB_DRIVER: ${DBCONSUMER_DB_DRIVER}
      DB_URL: ${DBCONSUMER_DB_URL}
      DB_USERNAME: ${DBCONSUMER_DB_USERNAME}
      DB_PASSWORD: ${DBCONSUMER_DB_PASSWORD}
      ALERT_ADDRESSES: ${DBCONSUMER_ALERT_ADDRESSES}
      FROM_EMAIL: ${DBCONSUMER_FROM_EMAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      POOL_SIZE: ${DBCONSUMER_POOL_SIZE}
      ENV: ${DBCONSUMER_ENV}
    logging:
      options:
        max-size: 50m

  milepost-graph-db:
    build: milepost-graph-db
    restart: always
    ports:
      - '6474:7474'
      - '6473:7473'
      - '6687:7687'
    volumes:
      - ./milepost-graph-db/neo-data/plugins:/var/lib/neo4j/plugins
      
      - ./milepost-graph-db/neo-data/import:/var/lib/neo4j/import
      
      - ./milepost-graph-db/neo-data/conf:/var/lib/neo4j/conf
      
      - ./milepost-graph-db/neo-data/data:/var/lib/neo4j/data

    environment:
      NEO4J_AUTH: none
