server.port=8888

config.dbUrl=${CONFIG_DB_URL}
config.dbUsername=${CONFIG_DB_USERNAME}
config.dbPassword=${CONFIG_DB_PASSWORD}

config.maximumPoolSize=7
config.connectionTimeout=300000

config.alertAddresses=user@example.com,user2@example.com
config.fromEmail=support@example.com
config.environmentName=DEV
config.mailHost=127.0.0.1
config.mailPort=25

# server.ssl.key-store: classpath:keystore.jks
# server.ssl.key-store-password: store-password
# server.ssl.keyStoreType: JKS
# server.ssl.keyAlias: some-alias

logging.level.root=INFO