config.odeUrl=${CONFIG_ODE_URL}
config.sdwTtl=oneyear
config.cvRestService=${CONFIG_CV_REST_SERVICE}
config.sdwRestUrl=${CONFIG_SDW_REST_URL}
config.sdwApiKey=${CONFIG_SDW_API_KEY}
config.defaultLaneWidth=50
# Note the rsuRoutes will need to reflect what's passed in, and what is in the rsu_view view
config.rsuRoutes = route1, route2
config.pointIncidentBufferMiles=1
config.alertAddresses=user@example.com,user2@example.com
config.fromEmail=support@example.com
config.environmentName=${CONFIG_ENVIRONMENT_NAME:DEV}
config.mailHost=${CONFIG_MAIL_HOST}
config.mailPort=25

# second minute hour day month day-of-week
cron.expression=0 0 1 * * *