server.port=7777

config.odeUrl=${CONFIG_ODE_URL}
config.dbUrl=${CONFIG_DB_URL}
config.dbUsername=${CONFIG_DB_USERNAME}
config.dbPassword=${CONFIG_DB_PASSWORD}
config.maximumPoolSize=7
config.connectionTimeout=300000
config.env=dev

config.sdwRestUrl=https://sdx.trihydro.com/
config.sdwApiKey=<apikey>
config.alertAddresses=user@example.com,user2@example.com
config.fromEmail=support@example.com
config.environmentName=DEV
config.dotGnisId=${WRAPPER_CONFIG_DOT_GNIS_ID:000000}
config.mailHost=${CONFIG_MAIL_HOST}
config.mailPort=${CONFIG_MAIL_PORT}
config.defaultLaneWidth=50
config.cvRestService=${CONFIG_CV_REST_SERVICE}
config.httpLoggingMaxSize=2000
# Note the rsuRoutes will need to reflect what's passed in, and what is in the rsu_view view
config.rsuRoutes=route1, route2
config.pointIncidentBufferMiles=1
config.sdwTtl=oneyear

# server.ssl.key-store: classpath:keystore.jks
# server.ssl.key-store-password:password
# server.ssl.keyStoreType: JKS
# server.ssl.keyAlias: some-alias