services:
  postgres:
    image: postgis/postgis:15-master
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdb:/var/lib/postgresql/data
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}
  # end of external dependencies ----------------------------------------------

  # timm apps --------------------------------------------------------------
  cv-data-controller:
    build: ../cv-data-controller
    restart: always
    ports:
      - "8888:8888"
    environment:
      SERVER_PORT: 8888
      CONFIG_DB_URL: jdbc:postgresql://${POSTGRES_DB_HOSTNAME}:5432/${POSTGRES_DB_NAME}?user=${POSTGRES_USER}
      CONFIG_DB_USERNAME: ${POSTGRES_USER}
      CONFIG_DB_PASSWORD: ${POSTGRES_PASSWORD}
      CONFIG_MAXIMUM_POOL_SIZE: 7
      CONFIG_CONNECTION_TIMEOUT: 300000
      CONFIG_ODE_URL: http://${DOCKER_HOST_IP}:8080
      CONFIG_ENV: local
      SPRING_DATA_NEO4J_URI: ${NEO4J_URI:-bolt://localhost:6687}
      CONFIG_ALERT_ADDRESSES: test@gmail.com
      CONFIG_FROM_EMAIL: test@gmail.com
      CONFIG_ENVIRONMENT_NAME: local
      CONFIG_MILEPOST_PROVIDER: ${MILEPOST_PROVIDER:-gis}
      CONFIG_MAIL_HOST: 172.0.0.1
      CONFIG_MAIL_PORT: 123
      LOGGING_LEVEL_COM_TRIHYDRO: ${LOGGING_LEVEL_COM_TRIHYDRO}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}

  ode-wrapper:
    build: ../ode-wrapper
    restart: always
    environment:
      SERVER_PORT: 7777
      CONFIG_ODE_URL: http://${DOCKER_HOST_IP}:8080
      CONFIG_ENV: local
      CONFIG_SDW_TTL: oneday
      CONFIG_SDW_REST_URL: ${SDW_REST_URL}
      CONFIG_SDW_API_KEY: ${SDW_API_KEY}
      CONFIG_ALERT_ADDRESSES: test@gmail.com
      CONFIG_FROM_EMAIL: test@gmail.com
      CONFIG_MAIL_HOST: 172.0.0.1
      CONFIG_MAIL_PORT: 123
      CONFIG_ENVIRONMENT_NAME: local
      CONFIG_DEFAULT_LANE_WIDTH: 50
      CONFIG_CV_REST_SERVICE: http://${DOCKER_HOST_IP}:8888
      CONFIG_HTTP_LOGGING_MAX_SIZE: 2000
      CONFIG_RSU_ROUTES: ${RSU_ROUTES}
      CONFIG_POINT_INCIDENT_BUFFER_MILES: 1
      CONFIG_DOT_GNIS_ID: ${DOT_GNIS_ID}
      LOGGING_LEVEL_COM_TRIHYDRO: ${LOGGING_LEVEL_COM_TRIHYDRO}
    healthcheck:
      test: ["CMD", "curl", "http://${DOCKER_HOST_IP}:7777/rw-tim/"]
    ports:
      - "7777:7777"
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}

  rsu-data-controller:
    build: ../rsu-data-controller
    restart: always
    ports:
      - "8898:8898"
    environment:
      SERVER_PORT: 8898
      CONFIG_SNMP_RETRIES: 3
      CONFIG_SNMP_TIMEOUT_SECONDS: 15
      CONFIG_SNMP_USER_NAME: testusername
      CONFIG_SNMP_AUTH_PASSPHRASE: testpassword
      CONFIG_SNMP_AUTH_PROTOCOL: SHA
      CONFIG_SNMP_SECURITY_LEVEL: authNoPriv
      DB_URL: jdbc:postgresql://${POSTGRES_DB_HOSTNAME}:5432/${POSTGRES_DB_NAME}?user=${POSTGRES_USER}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      MAXIMUM_POOL_SIZE: 13
      CONNECTION_TIMEOUT: 300000
      LOGGING_LEVEL_COM_TRIHYDRO: ${LOGGING_LEVEL_COM_TRIHYDRO}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}

  cv-data-tasks:
    build: ../cv-data-tasks
    restart: always
    environment:
      CONFIG_ODE_URL: http://${DOCKER_HOST_IP}:8080
      CONFIG_CV_REST_SERVICE: http://${DOCKER_HOST_IP}:8888
      CONFIG_CV_REST_SERVICE_DEV: http://${DOCKER_HOST_IP}:8888
      CONFIG_CV_REST_SERVICE_PROD: http://${DOCKER_HOST_IP}:8888
      CONFIG_RSU_DATA_SERVICE_URL: http://${DOCKER_HOST_IP}:8898
      CONFIG_WRAPPER_URL: http://${DOCKER_HOST_IP}:7777
      CONFIG_MAIL_HOST: 172.0.0.1
      CONFIG_MAIL_PORT: 123
      CONFIG_ENVIRONMENT_NAME: local
      CONFIG_SDW_REST_URL: ${SDW_REST_URL}
      CONFIG_SDW_API_KEY: ${SDW_API_KEY}
      CONFIG_TMDD_URL: http://testurl
      CONFIG_TMDD_USER: testusername
      CONFIG_TMDD_PASSWORD: testpassword
      CONFIG_ALERT_ADDRESSES: test@gmail.com
      CONFIG_FROM_EMAIL: test@gmail.com
      CONFIG_RUN_TMDD_VALIDATION: false
      CONFIG_RUN_RSU_VALIDATION: false
      CONFIG_RSU_VALIDATION_DELAY_SECONDS: 60
      CONFIG_RSU_VAL_THREAD_POOL_SIZE: 4
      CONFIG_RSU_VAL_TIMEOUT_SECONDS: 300
      CONFIG_REMOVE_EXPIRED_PERIOD_MINUTES: 240
      CONFIG_CLEANUP_PERIOD_MINUTES: 240
      CONFIG_SDX_VALIDATION_PERIOD_MINUTES: 1440
      CONFIG_RSU_VALIDATION_PERIOD_MINUTES: 240
      CONFIG_TMDD_VALIDATION_PERIOD_MINUTES: 1440
      CONFIG_RETENTION_ENFORCEMENT_PERIOD_MINUTES: 1440
      CONFIG_RETENTION_REMOVE_TIMS: true
      CONFIG_RETENTION_REMOVE_STATUS_LOGS: false
      CONFIG_HSM_FUNCTIONALITY_MINUTES: 1
      CONFIG_HSM_URL: http://testurl
      CONFIG_HSM_ERROR_EMAIL_FREQUENCY_MINUTES: 10
      CONFIG_RUN_HSM_CHECK: false
      CONFIG_SDW_TTL: oneyear
      CONFIG_DEFAULT_LANE_WIDTH: 50
      CONFIG_RSU_ROUTES: ${RSU_ROUTES}
      CONFIG_POINT_INCIDENT_BUFFER_MILES: 1
      CONFIG_CLEANUP_STALE_ACTIVE_TIM_HOLDING_RECORDS_PERIOD_MINUTES: ${TASKS_CONFIG_CLEANUP_STALE_ACTIVE_TIM_HOLDING_RECORDS_PERIOD_MINUTES}
      LOGGING_LEVEL_COM_TRIHYDRO: ${LOGGING_LEVEL_COM_TRIHYDRO}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}
    depends_on:
      ode-wrapper:
        condition: service_healthy
      cv-data-controller:
        condition: service_started
      rsu-data-controller:
        condition: service_started
  
  tim_logger:
    build: ../ode-data-logger
    restart: always
    environment:
      KAFKA_HOST_SERVER: ${DOCKER_HOST_IP}
      ALERT_ADDRESSES: test@gmail.com
      FROM_EMAIL: test@gmail.com
      ENVIRONMENT_NAME: local
      MAIL_HOST: 172.0.0.1
      MAIL_PORT: 123
      DEPOSIT_TOPIC: topic.OdeTimJson
      DEPOSIT_GROUP: group_tim_logger
      CV_REST_SERVICE: http://${DOCKER_HOST_IP}:8888
      PRODUCER_TOPIC: topic.OracleDataLogger
      ENV: local
      LOGGING_LEVEL_COM_TRIHYDRO: ${LOGGING_LEVEL_COM_TRIHYDRO}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}

  logger-kafka-consumer:
    build: ../logger-kafka-consumer
    restart: always
    environment:
      DEPOSIT_GROUP: logger_group_deposit
      DEPOSIT_TOPIC: topic.OracleDataLogger
      KAFKA_HOST_SERVER: ${DOCKER_HOST_IP}
      MAX_POLL_INTERVAL_MS: 600000
      MAX_POLL_RECORDS: 25
      DB_URL: jdbc:postgresql://${POSTGRES_DB_HOSTNAME}:5432/${POSTGRES_DB_NAME}?user=${POSTGRES_USER}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      MAXIMUM_POOL_SIZE: 13
      CONNECTION_TIMEOUT: 300000
      ALERT_ADDRESSES: test@gmail.com
      FROM_EMAIL: test@gmail.com
      ENVIRONMENT_NAME: local
      MAIL_HOST: 172.0.0.1
      MAIL_PORT: 123
      ENV: local
      LOGGING_LEVEL_COM_TRIHYDRO: ${LOGGING_LEVEL_COM_TRIHYDRO}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}

  tim-refresh:
    build: ../tim-refresh
    restart: always
    environment:
      CONFIG_ODE_URL: http://${DOCKER_HOST_IP}:8080
      CONFIG_SDW_TTL: oneyear
      CONFIG_CV_REST_SERVICE: http://${DOCKER_HOST_IP}:8888
      CONFIG_SDW_REST_URL: ${SDW_REST_URL}
      CONFIG_SDW_API_KEY: ${SDW_API_KEY}
      CONFIG_DEFAULT_LANE_WIDTH: 50
      CONFIG_RSU_ROUTES: ${RSU_ROUTES}
      CONFIG_POINT_INCIDENT_BUFFER_MILES: 1
      CRON_EXPRESSION: ${REFRESH_CRON_EXPRESSION}
      CONFIG_ENV: local
      CONFIG_ALERT_ADDRESSES: test@gmail.com
      CONFIG_FROM_EMAIL: test@gmail.com
      CONFIG_ENVIRONMENT_NAME: local
      CONFIG_MAIL_HOST: 172.0.0.1
      CONFIG_MAIL_PORT: 123
      LOGGING_LEVEL_COM_TRIHYDRO: ${LOGGING_LEVEL_COM_TRIHYDRO}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}

  cert-expiration:
    build: ../cert-expiration
    restart: always
    environment:
      KAFKA_HOST_SERVER: ${DOCKER_HOST_IP}
      ALERT_ADDRESSES: test@gmail.com
      FROM_EMAIL: test@gmail.com
      ENVIRONMENT_NAME: local
      MAIL_HOST: 172.0.0.1
      MAIL_PORT: 123
      DEPOSIT_TOPIC: topic.OdeTIMCertExpirationTimeJson
      DEPOSIT_GROUP: certExpirationGroup
      CV_REST_SERVICE: http://${DOCKER_HOST_IP}:8888
      PRODUCER_TOPIC: topic.OracleDataLogger
      LOGGING_LEVEL_COM_TRIHYDRO: ${LOGGING_LEVEL_COM_TRIHYDRO}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}

  tim_logger_mongo:
    build: ../ode-mongo-logger
    restart: always
    environment:
      MONGOLOGGER_DEPOSIT_TOPIC: topic.OdeTimJson
      MONGOLOGGER_DEPOSIT_GROUP: group_tim_mongo_logger
      MONGOLOGGER_HOSTNAME: ${DOCKER_HOST_IP}
      MONGOLOGGER_MONGO_HOST: mongo
      MONGOLOGGER_MONGO_DATABASE: local
      MONGOLOGGER_MONGO_AUTH_DATABASE: admin
      MONGOLOGGER_MONGO_USERNAME: ${MONGO_USER}
      MONGOLOGGER_MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGOLOGGER_ALERT_ADDRESSES: test@gmail.com
      MONGOLOGGER_FROM_EMAIL: test@gmail.com
      MONGOLOGGER_ENVIRONMENT_NAME: local
      MONGOLOGGER_MAIL_HOST: 172.0.0.1
      MONGOLOGGER_MAIL_PORT: 123
      LOGGING_LEVEL_COM_TRIHYDRO: ${LOGGING_LEVEL_COM_TRIHYDRO}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}

  bsm_logger_mongo:
    build: ../ode-mongo-logger
    restart: always
    environment:
      MONGOLOGGER_DEPOSIT_TOPIC: topic.OdeBsmJson
      MONGOLOGGER_DEPOSIT_GROUP: group_bsm_mongo_logger
      MONGOLOGGER_HOSTNAME: ${DOCKER_HOST_IP}
      MONGOLOGGER_MONGO_HOST: mongo
      MONGOLOGGER_MONGO_DATABASE: local
      MONGOLOGGER_MONGO_AUTH_DATABASE: admin
      MONGOLOGGER_MONGO_USERNAME: ${MONGO_USER}
      MONGOLOGGER_MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGOLOGGER_ALERT_ADDRESSES: test@gmail.com
      MONGOLOGGER_FROM_EMAIL: test@gmail.com
      MONGOLOGGER_ENVIRONMENT_NAME: local
      MONGOLOGGER_MAIL_HOST: 172.0.0.1
      MONGOLOGGER_MAIL_PORT: 123
      LOGGING_LEVEL_COM_TRIHYDRO: ${LOGGING_LEVEL_COM_TRIHYDRO}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}

  driveralert_logger_mongo:
    build: ../ode-mongo-logger
    restart: always
    environment:
      MONGOLOGGER_DEPOSIT_TOPIC: topic.OdeDriverAlertJson
      MONGOLOGGER_DEPOSIT_GROUP: group_da_mongo_logger
      MONGOLOGGER_HOSTNAME: ${DOCKER_HOST_IP}
      MONGOLOGGER_MONGO_HOST: mongo
      MONGOLOGGER_MONGO_DATABASE: local
      MONGOLOGGER_MONGO_AUTH_DATABASE: admin
      MONGOLOGGER_MONGO_USERNAME: ${MONGO_USER}
      MONGOLOGGER_MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGOLOGGER_ALERT_ADDRESSES: test@gmail.com
      MONGOLOGGER_FROM_EMAIL: test@gmail.com
      MONGOLOGGER_ENVIRONMENT_NAME: local
      MONGOLOGGER_MAIL_HOST: 172.0.0.1
      MONGOLOGGER_MAIL_PORT: 123
      LOGGING_LEVEL_COM_TRIHYDRO: ${LOGGING_LEVEL_COM_TRIHYDRO}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE}
        max-file: ${LOGGING_OPTIONS_MAX_FILES}
  # end of timm apps ---------------------------------------------------------

# volumes ---------------------------------------------------------------------
volumes:
  kafka:
    { }
  pgdb:
    driver: local
  mongodb_data_container:
# end of volumes ---------------------------------------------------------------