server.port=8898
config.snmpRetries=3
config.snmpTimeoutSeconds=5
config.snmpUserName=username
config.snmpAuthPassphrase=password
config.snmpAuthProtocol=SHA
config.snmpSecurityLevel=authNoPriv

dbUrl=${CONFIG_DB_URL}
dbUsername=${CONFIG_DB_USERNAME}
dbPassword=${CONFIG_DB_PASSWORD}

maximumPoolSize=13
connectionTimeout=300000